//
// Created by Hao-En Sung on 12/21/21.
//

#ifndef MAHJONG_LEARNING_C_TILESETS_TILESET_H_
#define MAHJONG_LEARNING_C_TILESETS_TILESET_H_

class Tileset {

};

#endif //MAHJONG_LEARNING_C_TILESETS_TILESET_H_
